<?php

/*
 * phpMyEdit language file
 *
 * language: tamil (indian)
 * encoding: utf-8
 * date: 2020-10-06
 * author: Ap.Muthu <apmuthu@usa.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.EN.inc,v 1.11 2004/12/27 20:14:29 nepto Exp $ */

return Array(
		'Add'           	=>'சேர்',
		'Copy'           	=>'நகல்',
		'Change'        	=>'மாற்றம்',
		'Delete'        	=>'நீக்கு',
		'View'  	   	 	=>'காண்க',
		'Prev'          	=>'முன்',
		'Next'          	=>'அடுத்த',
		'First'         	=>'முதல்',
		'Last'          	=>'கடைசி',
		'Go to'         	=>'சென்று',
		'Page'          	=>'பக்கம்',
		'Records'       	=>'பதிவுகள்',
		'Save'          	=>'சேமி',
		'More'          	=>'மேலும்',
		'Apply'         	=>'விண்ணப்பி',
		'Cancel'        	=>'ரத்து',
		'Search'			=>'தேடல்',
		'Hide'				=>'மறை',
		'Clear'				=>'அழி',
		'Query'				=>'வினவல்',
		'Current Query'		=>'தற்போதைய வினவல்',
		'Sorted By'			=>'வரிசைப்படுத்தப்பட்டுள்ளது',
		'ascending'			=>'ஏறுதல்',
		'descending'		=>'இறங்குதல்',
		'hidden'			=>'மறைத்து',
		'of'				=>'இன்',
		'record added'  	=>'பதிவு சேர்க்கப்பட்டது',
		'record changed'	=>'பதிவு மாற்றப்பட்டது',
		'record deleted'	=>'பதிவு நீக்கப்பட்டது',
		'Please enter'  	=>'தயவுசெய்து உள்ளீடவும்',
		'months' => Array(
			'01'=>'ஜனவரி',
			'02'=>'பிப்ரவரி',
			'03'=>'மார்ச்',
			'04'=>'ஏப்ரல்',
			'05'=>'மே',
			'06'=>'ஜூன்',
			'07'=>'ஜூலை',
			'08'=>'ஆகஸ்ட்',
			'09'=>'செப்டம்பர்',
			'10'=>'அக்டோபர்',
			'11'=>'நவம்பர்',
			'12'=>'டிசம்பர்'),
		// phpMyEdit-report
		'Make report'			=> 'அறிக்கை செய்',
		'Select fields'			=> 'ுலங்களைத் தேர்ந்தெடு',
		'Records per screen'	=> 'ஒரு திரைக்கு பதிவுகள்',
		);

?>
